create table if not exists public.installment_orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_name text,
  customer_phone text,
  delivery_state text,
  model text,
  capacity text,
  color text,
  phone_price numeric,
  down_payment_percent numeric,
  down_payment_amount numeric,
  term_months integer,
  monthly_payment numeric,
  identity_card_url text,
  salary_slip_url text,
  bank_statement_url text,
  cloudinary_assets jsonb,
  source text default 'website'
);

alter table public.installment_orders enable row level security;

create policy "service role can manage installment orders"
on public.installment_orders
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

insert into storage.buckets (id, name, public)
values ('installment-documents', 'installment-documents', false)
on conflict (id) do nothing;
